### ISSUE TITLE
Codeblocks: comments aren't being correctly rendered when removed

### ISSUE THREAD

**Issue by lepeli** [streetwriters/notesnook#1770]
### What happened?

When removing a comment in a yaml file it doesn't show as uncommented.
Works with adding a comment and then removing it.

[Screencast.webm](https://user-images.githubusercontent.com/24854702/214055657-a66aeb27-e64b-481b-bf9e-fe3136d95cad.webm)

### Steps to reproduce the problem

Remove a comment from a line.
Or comment a line and uncomment it.

```yaml
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=aaa
      - --oidc-client-id=
      - --oidc-client-secret=
      - --oidc-extra-scope=
      # - --insecure-skip-tls-verify
      - --grant-type=authcode-keyboard 
```

### Version

version 2.4.0-9e382b1-web

### Platform/OS

Firefox
