### ISSUE TITLE
The Last Flatpak Update of the App Made It Nonfunctional

### ISSUE THREAD

**Issue by DanielProg39** [streetwriters/notesnook#6967]
### What happened?

I don't know if this is a problem with all editions of the app or just the Flatpak package, but after the latest update it won't open.

### Steps to reproduce the problem

Install or update the Flatpak version of Notesnook to version 3.0.21 and try to open it.

### Version

3.0.21

### Platform/OS

Linux

### Relevant log output

```shell
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/app/bin/resources/app/build/electron.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:120689)
    at node:electron/js2c/browser_init:2:126189
    at node:electron/js2c/browser_init:2:126438
    at node:electron/js2c/browser_init:2:126442
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:104:7)
    at Module._load (node:internal/modules/cjs/loader:1083:17)
    at c._load (node:electron/js2c/node_init:2:16955)
```

**Comment by hasib-rozi** [comment]
Me too. Restarting the system didn't solve the problem either.

**Comment by franjsco** [comment]
Same here. After updating via Flatpak, it gives an error.

Version: 3.0.21
OS: Linux (Fedora 41)

out:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/app/bin/resources/app/build/electron.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:120689)
    at node:electron/js2c/browser_init:2:126189
    at node:electron/js2c/browser_init:2:126438
    at node:electron/js2c/browser_init:2:126442
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:398:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:337:10)
    at loadBuiltinModule (node:internal/modules/helpers:104:7)
    at Module._load (node:internal/modules/cjs/loader:1083:17)
    at c._load (node:electron/js2c/node_init:2:16955)

[3:1123/161657.042388:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: File o directory non esistente
[3:1123/161657.042429:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: File o directory non esistente
```

**Comment by saulfgonzalez** [comment]
Same here. The app won't launch and I get the exact same error.

**Comment by ibaraki-douji** [comment]
3.0.22 as well same error

**Comment by ubiquities** [comment]
I received the same error
V3.0.22
Linux Mint

Happened on 2 different devices
One fresh install and one upgrade

**Comment by ibaraki-douji** [comment]
@OstapTelychko 
You can run this command : `flatpak update --commit=bf47df73021c93fa79c1ec89b81ebd7d987f437800e07ef89da72404e4ac7597 com.notesnook.Notesnook` (add `sudo` if it doesn't work, might be because it's installed as system app and not user app)

for the commit code i used the one just before the 3.0.21 release and it works.
Here is all the commit codes from 3.0.19 to 3.0.22

```
    Commit: f2e70a7d9c431a677b744a0176fb47e1193c49c7114fe87c9cd71efaf2bb566c
    Parent: 289b1a27c55168d6e1b312bcf5bee829a69cd7573911b0e00679f4796b84151f
   Subject: v3.0.22 (#59) (cf8cd570)
      Date: 2024-11-23 14:36:57 +0000
   History: 

    Commit: 289b1a27c55168d6e1b312bcf5bee829a69cd7573911b0e00679f4796b84151f
   Subject: V3.0.21 (#54) (99a7f3d4)
      Date: 2024-11-23 04:43:39 +0000

    Commit: bf47df73021c93fa79c1ec89b81ebd7d987f437800e07ef89da72404e4ac7597
   Subject: chore: bump runtimes to 24.08 (1eb03d03)
      Date: 2024-11-22 12:56:46 +0000

    Commit: 094b4e2510ab4e5832c0151b02308667b8da3da5f9b4be185bb0a95da991cbfc
   Subject: fix: wrong name for X11 fallback socket (3ee7ae6b)
      Date: 2024-11-22 05:26:32 +0000

    Commit: 27d65be64fd1b23319264d02c262da9d6a1df825d1a5bbd45164ff5e655a21be
   Subject: fix: export TMPDIR to fix tray icon not displaying (d78359e8)
      Date: 2024-11-22 02:28:25 +0000

    Commit: 0f0471b0736267e304710bca045a4773d73f6ac62c9b8f0c2c804b487a6d51bb
   Subject: V3.0.19 (#52) (618cf11a)
      Date: 2024-10-28 14:28:18 +0000
```
